### ISSUE TITLE
404 when trying to download request-built .deb

### ISSUE THREAD

**Issue by mbonaci** [andypetrella/spark-notebook#143]
I requested debian package build and got:

![image](https://cloud.githubusercontent.com/assets/497926/6991898/1689c372-daaf-11e4-9db0-b7a06dccff4b.png)

URL: https://s3.eu-central-1.amazonaws.com/spark-notebook/deb/spark-notebook_0.4.0-scala-2.10.4-spark-1.3.0-hadoop-2.4.0_all.deb

But when I try to download this is what happens:
```sh
mbo@mbo-sia:~/install$ wget https://s3.eu-central-1.amazonaws.com/spark-notebook/deb/spark-notebook_0.4.0-scala-2.10.4-spark-1.3.0-hadoop-2.4.0_all.deb
--2015-04-04 09:37:52--  https://s3.eu-central-1.amazonaws.com/spark-notebook/deb/spark-notebook_0.4.0-scala-2.10.4-spark-1.3.0-hadoop-2.4.0_all.deb
Resolving s3.eu-central-1.amazonaws.com (s3.eu-central-1.amazonaws.com)... 54.231.193.16
Connecting to s3.eu-central-1.amazonaws.com (s3.eu-central-1.amazonaws.com)|54.231.193.16|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-04-04 09:37:57 ERROR 404: Not Found.
```

BTW :+1:  x :100: 
This is just FYI, since I managed to download `zip` (can't wait to try it out).  
Thank you for making this available, you might have easily made a business out of it, considering how Spark's popularity is skyrocketing.

**Comment by andypetrella** [comment]
Heya,
Thanks for reporting there were actually two problems:
- the mail was misleading, it was providing download information while the generator was still building the distro -_-
- the deb package wasn't build because the machine missed a deb lib -_-"

It's now solved. But just one note, the debian package isn't very tested so if you find any problems using it I'll be very happy helping going through them to solve. But I hope there will be none of course.

Thanks for the kind words, I don't know if I could make some money but it's at least for now funny to do, thanks for contributors and users feedbacks!
For the rest, I thinking ;-)

Cheers,
andy

**Comment by mbonaci** [comment]
Yes, just checked, it's now fixed.  
Will report if I stumble on something.  
Thanks

**Comment by d10genes** [comment]
I'm getting this as well for the zip and tgz.

```
Build (retry #0)

notebook version : 0.4.1
scala version : 2.11.2
spark version : 1.3.0
hadoop version : 2.4.0
package type : tgz
```


```
$  wget https://s3.eu-central-1.amazonaws.com/spark-notebook/tgz/spark-notebook-0.4.1-scala-2.11.2-spark-1.3.0-hadoop-2.4.0.tgz
--2015-04-17 11:04:31--  https://s3.eu-central-1.amazonaws.com/spark-notebook/tgz/spark-notebook-0.4.1-scala-2.11.2-spark-1.3.0-hadoop-2.4.0.tgz
Resolving s3.eu-central-1.amazonaws.com... 54.231.192.45
Connecting to s3.eu-central-1.amazonaws.com|54.231.192.45|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-04-17 11:04:32 ERROR 404: Not Found.
```

I'm new to Spark/hadoop, should I be trying a different combination?

**Comment by andypetrella** [comment]
Oooops, did something bad with the merging → I merged the use of SBT for the deps management but it won't work with 2.11.2...
Do you need 2.11 absolutely? Because I'll have to patch that :-/

Sorry about that → will create an issue for that, thanks for reporting
