### ISSUE TITLE
Spark Notebook process "stops" when nohup'd

### ISSUE THREAD

**Issue by rnowling** [andypetrella/spark-notebook#155]
When Spark Notebook is run with `nohup`, the process stops.  To reproduce, run Spark Notebook as follows:

    $ nohup ./bin/spark-notebook &> nohup.log &

**Comment by maasg** [comment]
+1 me too. Same issue - doesn't want to run in the background.

**Comment by andypetrella** [comment]
until it's fixed (help is more than welcome in that one 😄),  you can use screen for that. it's what I do generally on ec2. but I know it's far from ideal...

**Comment by andypetrella** [comment]
@rnowling @maasg it should be fixed on spark 1.3.x now. 

I'll need to do it as well for previous versions if you need it -- I didn't spent the time yet because 1.2.x versions tend to be less and less used, but of course I'l against doing it if necessary ;-).

I know what was the problem so I should be able to figure out how to solve it for these versions too -- for the record: I was still starting the jline reader wrapper from the spark code, this guy waits on standard **input** but nohup [doesn't really support that](http://en.wikipedia.org/wiki/Nohup) (of course).

**Comment by rnowling** [comment]
Thank you @andypetrella !  I'll give it a try this week.  :)

**Comment by andypetrella** [comment]
KoOl ^^
