### ISSUE TITLE
notebooks.dir and other configs related to notebooks are not picked up

### ISSUE THREAD

**Issue by gauravkumar37** [andypetrella/spark-notebook#156]
Hi,

notebooks.dir and other configs related to notebooks are not picked up.
I looked at the code and found that the issue is because of the dot `.` in the property name. It tries to find `dir` inside a `notebooks` config.
I would suggest to create a `notebooks` inside `master` and there have the different properties for notebook such as `dir`, `name` etc.

Thanks
GK

**Comment by andypetrella** [comment]
Hello @gauravkumar37, 
Looks interesting but I'm not sure I got the issue behind. Could you give me an example of a use case  please? 
That would be fantastic 
Thanks man

**Comment by gauravkumar37** [comment]
Sure,
The config has a property `notebooks.dir`. But it never gets picked up. Instead, the default value `./conf/notebooks` is picked up. That is because the code is trying to read `notebooks.dir` which has a `.` in the property name and thinks that it is hierarchy base - `dir` property inside `notebooks` property.

**Comment by andypetrella** [comment]
Hello @gauravkumar37, just wanted to poke you on this one. My tests were okay using the property. Hence I've updated the code to add some debug logging regarding this value, so we can track it easily.

Also, note that the directory has to exist when the notebook server start otherwise it'll fallback on the default one.
