### ISSUE TITLE
sparkContext vs sc

### ISSUE THREAD

**Issue by maasg** [andypetrella/spark-notebook#163]
If you are used to the spark-shell, then you're also used to calling the spark context 'sc' and probably have a bunch of scripts that use that.
When adopting the spark-notebook, one should use `sparkContext` instead.  Of course, nothing stops me from doing `val sc = sparkContext` , but it would be great to have that alias built it.
WDYT?

Thanks, Gerard.

**Comment by andypetrella** [comment]
@maasg: There you go sir :-D

Using a `val` won't work because the `sparkContext` can be restarted, replaced, ... so it's a `var`. But using a `def` does the trick ^^

**Comment by petervandenabeele** [comment]
Hmmm ... this sounds less clean ?

What I practically do is define `val sc1`, `val sc2`, ... etc. as I go on with sparkContexts that have different properties (e.g. the number of CPU's and RAM to grab on the cluster etc.)

Maybe just do a `val` for the case based on "muscle memory" that @maasg  describes and force users to define `val sc1` if they really want to have specialized sparkContexts ?

**Comment by andypetrella** [comment]
@petervandenabeele actually you cannot have several contact within the same VM, hence within a notebook which is basically a driver. 

here the `def sc` is an alias, which I dislike in the context of a notebook, being something to be reused, shared, read or presented. 

`sc` is convenient is a repl where you want to save some typing for quick  expérimentations. 

So if you want to use the notebook likewise, you can now use `sc` here as well :-). 

Second to that, this is for people used with the repl only (e.g.  early adopters like @maasg ^^), being the tool for quick access to spark, specially for newcomers. However, people tend to say that it's even easier to try spark with the notebook because easier to install and start, plus the fact that there are a lot of examples. 

For instance, when I give the trainings, I don't impose the notebook and leave them first play with the repl, but it doesn't take minutes before they install the notebook 😄

**Comment by petervandenabeele** [comment]
Thanks for your detailed explanation :-)
