### ISSUE TITLE
application.conf not being parsed when running from distributed package

### ISSUE THREAD

**Issue by RPCMoritz** [andypetrella/spark-notebook#182]
Play server does not read application.conf when started in a distribution environment (i.e. zip), while still working when launched from sbt.

**Comment by andypetrella** [comment]
Right! Good catch. This is due to an upstep of the sbt native packager which now requires some additional configuration to take this one into account as well -- [ref](http://www.scala-sbt.org/sbt-native-packager/topics/play.html).

So there are two workaround (will see if it can come per default with the distro):

## use `conf/application.ini`
This file will be used to pass some arguments, including where the conf file is located. Hence you can create it with the following content

```
-Dconfig.file=./conf/application.conf
```

## from the script
Or you can simply pass this configuration to script:

```
./bin/spark-notebook -Dconfig.file=./conf/application.conf
```

![selfie-1](http://i.imgur.com/pctuIfv.png)
