### ISSUE TITLE
Spark Notebook integration with Hue

### ISSUE THREAD

**Issue by ogirardot** [andypetrella/spark-notebook#231]
The goal would be to have Spark Notebook run using Hue user credentials & impersonation brought by Hue. This would be an option to have multi user Spark notebooks (with segregation, access to data, ...). Joint effort with Hue project

**Comment by andypetrella** [comment]
Since I don't know hue much (besides the SQL capabilities and more or less the work they've apparently done with @velvia), I'm eagerly waiting to have more info about this ticket :-)

**Comment by YannBrrd** [comment]
The goal would be to have Spark Notebook run using Hue user credentials & impersonation brought by Hue. This would be an option to have multi user Spark notebooks (with segregation, access to data, ...). Joint effort with Hue project

**Comment by THABBuzzkill** [comment]
Spark Notebook is light-years ahead of Hue's concept of spark/scala notebooks in 3.8.1.  Marrying the capabilities of Spark Notebooks with the permissions model in Hue would be amazing.

Currently Hue's implementation of spark notebooks provides..
* User authentication / management, which integrates with HDFS
* Notebook sharing capabilities

Livy server, which provides the API that Hue's notebook system uses to interact with Spark, does not provide any kind of impersonation.  This means that all submitted jobs run as whatever process Livy is running as, which is a pretty gaping security hole.  If this can be addresses and Spark Notebook's is able to launch jobs as whoever is logged in (assuming, of course, that there is a 1 to 1 or some mapped relationship between Linux users and HDFS users), this would eliminate a lot of the security concerns that crop up.

**Comment by velvia** [comment]
Just an FYI, Andy and I had talked before about Spark Notebook working
together with Spark Job Server, and SJS is planning to add authentication
and permissions/roles.

On Thu, Jun 25, 2015 at 8:32 AM, THABBuzzkill <notifications@github.com>
wrote:

> Spark Notebook is light-years ahead of Hue's concept of spark/scala
> notebooks in 3.8.1. Marrying the capabilities of Spark Notebooks with the
> permissions model in Hue would be amazing.
>
> Currently Hue's implementation of spark notebooks provides..
>
>    - User authentication / management, which integrates with HDFS
>    - Notebook sharing capabilities
>
> Livy server, which provides the API that Hue's notebook system uses to
> interact with Spark, does not provide any kind of impersonation. This means
> that all submitted jobs run as whatever process Livy is running as, which
> is a pretty gaping security hole. If this can be addresses and Spark
> Notebook's is able to launch jobs as whoever is logged in (assuming, of
> course, that there is a 1 to 1 or some mapped relationship between Linux
> users and HDFS users), this would eliminate a lot of the security concerns
> that crop up.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andypetrella/spark-notebook/issues/231#issuecomment-115294630>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by ogirardot** [comment]
@velvia integrated with hue ?

**Comment by andypetrella** [comment]
@velvia that's great to know that SJS will add that, and indeed integrating with spark notebook is still planned -- maybe shall we create an issue where we can start thinking how we can start, or what we'll be needed before?

@folone @YannBrrd @THABBuzzkill I really have few ideas what HUE provides, like which kind of notebooks, how it deals interactively with spark and how impersonation works.
Do you think it would be possible to list these features and maybe giving hints/scenarii how you think they could be integrated into the notebook?


One thing: a notebook as a single session attached to which means that several persons are (will be) able to open a notebook and access the same session (and see live updates) -- that means that we'll need to keep this capability using roles, and also add roles like _opener_ that we'll bee allowed to close the opened session.
Indeed, a notebook is just a file (for now) in a folder so multiple sessions is not possible. So two users with different needs for a notebook (although, I don't see real use cases) will have to duplicate it with a different name.
Having users will also mean that folders will need access rights, which will be rather hard because a notebook can run any scala code, and it's still running co-locally with with the server. There are option of course like containers ;-).

So authentication and authorization are hard, very hard when we give access like this to the system. That's also why I still propose to create a spark notebook per user. A bit like each user has is own IDE.
This could be easily done using ... containers ^^ (and even more easily with marathon or alike).

Of course, this is not a solution for multi-users and collaboration, but for this I'm wondering how good would be a solution where the collaboration and others can be pushed to the repository of notebooks it self → a bit like github, in a sense.

It's just an idea, I don't know how it fits your need or will of course.

thanks all for your inputs!!!

PS: My feeling is that we'll have to split this issue a lil bit to target different underlying features.

**Comment by velvia** [comment]
@andypetrella @ogirardot separate tix sounds great.  
I actually don't know anything about Hue's security model, but it should be pluggable  :)

**Comment by romainr** [comment]
If I understood correctly the question is how we could bring multi-user support to the Spark Notebook with maybe Hue?

Hue is a single Web server that offers editors to multi users. It has a Notebook app in beta, which is "currently" very basic and focuses on Python, other SQL, deeper integration with Hadoop like HDFS, Hive tables autocompletes etc...

The Notebook relies on Livy, which is a new server that brings impersonation when used with Yarn, concurrent users, shell like capabilities, no code change or compilation needed: https://github.com/cloudera/hue/tree/master/apps/spark/java#welcome-to-livy-the-rest-spark-server

We initially used Spark Job Server from Ooyala but then switched to Livy as we wanted to focus on Shell-like features / Yarn impersonation instead of compiled jobs.

If I got it right, Spark Notebook is similar to Ipython, with one server by user.

For re-using Hue authentication for Spark Notebook, there is no easy way without integrating it in Hue as a new app (http://cloudera.github.io/hue/docs-3.8.0/sdk/sdk.html), which would not probably be simple as the projects are different and in a different language. We had several brainstorming about that in the past. This is why we started the Notebook UI natively in Hue.

If auth is native in Spark Notebook though, users could however submit Shell-like Scala snippets with Livy and this would require only one Spark Notebook and one Livy server in total. Obviously the REST API would need to be implemented and Livy is still new.

Hope it helps!

**Comment by andypetrella** [comment]
@romainr sorry for the radio silence, I'm in a rush for the next couple of days (talks to prepare) then I'll be  back on biz.
Thanks for the info btw, very helpful. I'll probably get back with some figures of the current behavior and we'll see how the integration could be done by then.

c u soon

**Comment by andypetrella** [comment]
@romainr @ogirardot @YannBrrd you guyz have a good understanding (of course) of HUE, as you can see, I'm lacking of time these days to create the right documentation to help us moving forward.

What about having an hangout so we can at least chat, and then we can make up our mind on what we'll be possible, but also, simply, what we'd like to have?

let me know!
Looking forward to this.

@velvia we've planned to hack on this integration during my trip to the US in August, so we'll be able to move this forward too on this track :-D

**Comment by YannBrrd** [comment]
Hi,

I think if we achieve #232 we can simply ignore this one... or postpone it...

Yann
