### ISSUE TITLE
Passing `-Dyarn.resourcemanager.am.max-attempts=1` to Spark processes

### ISSUE THREAD

**Issue by ryan-williams** [andypetrella/spark-notebook#300]
When I typically call `spark-submit`, I pass `-Dyarn.resourcemanager.am.max-attempts=1` to it; is there a way to configure spark-notebook to pass this or other similar non-Spark-conf params?

**Comment by andypetrella** [comment]
mmmmmh, I guess that you could do it however not at a notebook level, for this we'll probably need another extra metadata defining extra Java Properties to pass.

I think it'd be fair to add, no?

Besides this fact, in order to have this property pass to the notebook/driver's JVM you can use the `application.conf` key: [vmArgs](https://github.com/andypetrella/spark-notebook/blob/master/conf/application.conf#L94).
This guy will be provided as to all started processes.

**Comment by ryan-williams** [comment]
Yea, adding a way to do it via the "cluster" conf when spawning a new notebook would be nice.

Looking in to using `manager.kernel.vmArgs` to set it for all notebooks
