### ISSUE TITLE
kernel "should have a path actually" error message?

### ISSUE THREAD

**Issue by ryan-williams** [andypetrella/spark-notebook#323]
I just shutdown a notebook so that I could look at the executors' logs from YARN.

Then, I tried Kernel > Restart and Kernal > Reconnect to see if I could resuscitate the notebook; I don't see any signs of life in the notebook or the server logs about it, but I do see this on the "Running" screen:

![](http://f.cl.ly/items/2a3m3p3x252U1l1K242q/Screen%20Shot%202015-09-16%20at%205.32.10%20PM.png)

There is also this file in my `logs/` dir: `sn-session-3825c93e-de32-4c0f-97a8-5b18749f0644-no-path.log`

**Comment by andypetrella** [comment]
aha! Good catch, I think @jarutis saw that too. But now we have a kind of way to reproduce it!!
Cool.

It's probably linked to #270 then.
Sadly, I'll have few time until the week after to look at PR and bugs because of training. From last week of September, it should be more quiet and I'll get back more on the code side.

However, if you have an idea how to hack this up, feel free. I guess that the path got lost somewhere in the stop or restart process. A good example for test, but not so easy to test -_-.

So the "no-path" comes from the fact that indeed, we spawn a notebook (hence a [process](https://github.com/andypetrella/spark-notebook/blob/master/modules/subprocess/src/main/scala/notebook/kernel/remote/RemoteActorSystem.scala#L104))

Which means that [here](https://github.com/andypetrella/spark-notebook/blob/master/app/controllers/Application.scala#L433) either:
* `k` is none, which means that the kernelId is probably wrong or the KernelManager has a wrong cache
* or `k` has no `notebookPath` which is really weird :-/

So my best guess is that a crappy `kernelId` was sent...

---- 
However,

Looking quickly in the code, it should be safe, unless reconnect doesn't create a new kernel in js...
Which is the case, and in a sense normal, in the other weird because the kernel was killed.

Kernel.js → only restart the channels, [see](https://github.com/andypetrella/spark-notebook/blob/master/public/ipython/services/kernels/kernel.js#L343). Hence, rely on an existing kernel → [create WS](https://github.com/andypetrella/spark-notebook/blob/master/public/ipython/services/kernels/kernel.js#L442).

This will call [openKernel](https://github.com/andypetrella/spark-notebook/blob/master/app/controllers/Application.scala#L414) that only reconnects the WS...

Maybe there is a problem that actually restart should kill the kernel??? Which is weirdo to me.

If it's the case, hence restart should only stop the whole shebang while keeping the configuration and the kernelId live... glups it's very stateful alike, don't like that

**Comment by ryan-williams** [comment]
Just saw this again after "Shutdown"ing a notebook from the "Running" tab and then telling it to "Kernel > Restart":

![](http://cl.ly/image/1J032S3c430a/Screen%20Shot%202015-10-08%20at%205.10.27%20PM.png)

**Comment by andypetrella** [comment]
Oh okay, that's how can reproduce that.

Cool I'll check that then. It's certainly related to #270 ....
