### ISSUE TITLE
Skip dependency resolution when restarting notebook without changing metadata

### ISSUE THREAD

**Issue by ryan-williams** [andypetrella/spark-notebook#347]
It takes a few minutes for me to kernel-restart a notebook, it would be good to bring that time down. This seems like an obvious thing to skip where possible.

**Comment by andypetrella** [comment]
indeed, something I need to check, I think that the local repo is in front of the other, which should make the check quite fast, but not sure though

**Comment by andypetrella** [comment]
Right, @ryan-williams actually the local repo is always used first [see here](https://github.com/andypetrella/spark-notebook/blob/master/modules/common/src/main/scala-2.10/notebook/util/Deps.scala#L49). 

So there is little to do here :-(.

However, you might have this latency because you're not using a local repo? That would mean, indeed, that the repo is always created.
And even though, you have all deps locally in your .ivy2 for instance, the temp repo will copy everything in his own folder :-/.

It could be interesting to see if there is a simple way to share the temp repo across restart, but since it's enclosed in the ReplCalculator (which is teared down at restart), I don't expect a simple and elegant solution :-D

**Comment by ryan-williams** [comment]
I have my local Maven repository configured in the notebook, if that's what you mean.

I'll see if I can get a screen capture of what I mean; I can see in my console.log that the sbt resolution flow runs again when I restart even though I haven't changed any dependencies; presumably it's not downloading anything because it already previously downloaded all the dependencies, so it's just no-op'ing, but I'm not sure.

**Comment by andypetrella** [comment]
k,
I was talking about localRepo in metadata actually.

If you wanna check the downloads, the table is reporting you what's downloaded, what's not.

I'm gonna head to AMS for the spark summit, will try to follow up on that based on your next input :-)
cheers

**Comment by andypetrella** [comment]
@ryan-williams Hey mate, let me know if you're still seeing this.
I'll temporary move it to 0.7.0, before (I hope) closing it :-D
