### ISSUE TITLE
Spark 2 support

### ISSUE THREAD

**Issue by mozinrat** [andypetrella/spark-notebook#691]
Please excuse me if the issue is raised but I believe the night build already support spark 2.
Is there a way to download the build (.tgz) directly. If no can you publish the steps to build one for a novice.
Thanks

**Comment by andypetrella** [comment]
Hello, the spark 2 support is in another branch because this new version  offers us a better architecture, so it's very different from the master... 
building steps can be found in the documentation folder 
but you can also use http://spark-notebook.io and select master for the notebook version (important!...  the generator I'll use the correct future-master branch behind)

**Comment by mozinrat** [comment]
@andypetrella  thanks for reply but on spark-notebook.io it give me message like Build not available, but launched!. What am i missing

**Comment by andypetrella** [comment]
actually you should get a mail when the build will be finished
