### ISSUE TITLE
Open notebooks from any folder

### ISSUE THREAD

**Issue by lucaventurini** [andypetrella/spark-notebook#85]
In Ipython, the command `ipython notebook` can be called from any directory, launching a web service with all the .ipynb in the current directory and subdirs.

It would be useful to mantain the same approach, to store the notebooks within the projects / git repos / etc.

**Comment by andypetrella** [comment]
That's indeed interesting!
I've to work on the Tree implementation so that it can at least work with.... nah, tree structures :-).

I your case, it would be interesting to test with the command
`spark-notebook -Dmanager.notebook.dirs="."`

This should override the default directory (`./conf/notebooks`).

**Comment by lucaventurini** [comment]
Seems not that easy...

```
! @6l47doeed - Internal server error, for (GET) [/api/contents/?type=directory&_=1422955605195] ->

```

**Comment by andypetrella** [comment]
snap :-D.

Okay I'll take a look, and make sure this (at least) will work in the next release.
Thanks a lot for trying

**Comment by andypetrella** [comment]
Okay, got it. In order for it to work we need to use the current directory, otherwise the spark-notebook will take its pwd as cwd.
So rather than using `"."`, we can use `` `pwd ` `` like so:
```
spark-notebook -Dmanager.notebooks.dir=`pwd`
``` 

I know it's less sexy, but does the job for now. At some point, it would be interesting to add this option to the bin itself.
