### ISSUE TITLE
Dependencies are not updated

### ISSUE THREAD

**Issue by lucaventurini** [andypetrella/spark-notebook#87]
Executing "Update classpath and Spark's jars", it seems the dependencies are not updated as documented. 

At the end of the execution, the key `spark.jars` is still empty.

Also, trying to add mllib with the following code doesn't have any effect:

```
:dp org.apache.spark  % "spark-mllib_2.10" % 1.2.0
```

**Comment by andypetrella** [comment]
okay,I sometime experienced some latency or even exceptions.
The problem being that they aren't well reported.

Could you have a look in the logs and see if there are problems reported for this? 

A good practice, for perf reason, is to set the local-repo to be the .m2/repository. **The absolute path**, there is a problem using `~` for instance:
```
:local-repo /home/.../.m2/repository
```
Note that it will sadly fail if you're trying to use ivy2 repo :-/. Sorry about that.

Another remark or hint, the sparkContext has to restart (which is not yet visible in the UI, but I'm looking for ways reporting this thingy), so it also might be that you're seeing the "previous" sparkContext.

**Comment by andypetrella** [comment]
Oh wait I think I got it... and it's probably my fault for two reasons: 
* I didn't put enough accent on it since it's an habit we have I got rid of.
* there is no feedback on failure for this one

Actually, the problem should be that the `artifactId` is between quotes which will be included in the search... like this `"\"spark-mllib_2.'e;10\""` *sight*.

So the very first try I'd do is to remove 'em and on my side I'll remove them I they're provided.

you can poke me on gitter as well if you like

**Comment by lucaventurini** [comment]
Ok, this specific issue itself was rather generated by the fact I was executing this:
```
//:dp org.bdgenomics.adam % adam-apis % 0.15.0
:dp org.apache.spark % spark-mllib_2.10 % 1.2.0
```
that, I believe, resulted in executing nothing (how come?). Removing the first line gives me at least some errors in the logs, and I think they are caused by the proxy. Should I set something other than the usual `HTTP_PROXY`?

**Comment by andypetrella** [comment]
ah nice.
Indeed, the context built upon the `:<ctxt>` needs to start with this declaration. This should be in the doc! But it's not yet, although I can at least parse the code to detect and remove the comments.

For the proxy, I'll need to investigate I guess that aether should be instrumented in a way or another to be able to use a proxy. The current code doesn't take any care of that, see [here](https://github.com/andypetrella/spark-notebook/blob/master/modules/common/src/main/scala/notebook/util/Deps.scala#L115)

This is a clue of what should be done (hence modified in `Deps`) in order to have this working: https://github.com/jcabi/jcabi-aether/blob/master/src/main/java/com/jcabi/aether/Repository.java#L74

**Comment by lucaventurini** [comment]
At least, it seems working without the proxy, now that I had the chance to try.

Just, one loses hope a bit, without having any hint of the progress behind, and it can really take a while. Also, if the update fails for any reason, we will see that `[*]` forever, until we are clever enough to retry.

Maybe some log, at least a FAILED, should be passed to the notebook.

**Comment by andypetrella** [comment]
you're definitively right, I need to improve the feedback of this
dependency thingy.
I guess that aether is giving some but they're swallowed by the current
process.
leurs create issue of these two and close this one since it "can" work 😉

Le mer 4 févr. 2015 18:03, lucaventurini <notifications@github.com> a
écrit :
